apiVersion: v1
kind: Service
metadata:
  name: dsd-pod-3-service
  namespace : {{ .Release.Namespace }}
spec:
  # label keys and values that must match in order to receive traffic for this service
  selector:
    deployment: dsd-pod-3
    node: dsd-pod-3
  ports:
    # ports that this service should serve on
    - name: binary-secure
      protocol: TCP
      port: 22
