{{ if and (not (eq .Values.dsd.subscription.username "")) (not (eq .Values.dsd.subscription.password "")) }}

{{- $username := .Values.dsd.subscription.username }}
{{- $password := .Values.dsd.subscription.password }}
{{- $email := .Values.dsd.subscription.username }}
{{- $regId := default "docker.dsd.com" .Values.dsd.dockerRegistry }}
{{- $auth := printf "%s:%s" $username $password | b64enc }}
{{- $files := .Files }}
apiVersion: v1
kind: Secret
metadata:
  name: dsd-private-registry-creds
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $files.Get "auth.json" | replace "reg.id" $regId | replace "docker.dsd.username" $username | replace "docker.dsd.password" $password | replace "docker.dsd.email" $email | replace "docker.dsd.auth" $auth | b64enc }}
{{ end }}
